### ISSUE TITLE
Introduce 2 new APIs to validate paths exist and possibly mutate them

### ISSUE THREAD

**Issue by felipesere** [felipesere/yaml-navigator#7]
Given the YAML
```yaml
kind: foo
metadata:
  labels:
    app: foo
  annotations:
    owners: bar
spec:
  template:
    metadata:
      labels:
        app: foo
```
i want to be able to write a query that validate that "every metadata object has annotations, and every annotations object has an annotation called 'owner'".

Using the normal iteration would yield '.metadata.annotations.owner' but never 'spec.template.metadata' as its simply not present in the document.

```rust
let metadata = query!["...", "metadata"];
let check = query!["annotations", "owner"]; 

// the first query `metadata` represents the items we want to yield
// check is a subquery to decided if found matches should be yielded
for (ctx, metadata) in yaml_navigator::ensure(doc, metadata, check) {
  // would yield .spec.template.metadata as the `check` query was unsuccessful
}

let update_metadata = yaml_navigator::ensure_mut(&mut doc, metadata, check);
while let Some((ctx, metadata) = update_metadata.next() {
  // yields a mutable reference to `metadata` to then modify whatever is needed
}
```
